name: Sync to GitLab

on:
  push:
    branches:
      - main  # change if your branch is not 'main'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "deeprajchouhaniflair@gmail.com"
          git config --global user.name "DeepRajBytes"

      - name: Add GitLab remote and push
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/deeprajchouhaniflair/JewelTrain-backend.git || echo "Remote already exists"
          git fetch gitlab
          git push gitlab main --force
