name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change this if your branch is not 'main'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.email "deeprajchouhaniflair@gmail.com"
          git config --global user.name "DeepRajBytes"

          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/deeprajchouhaniflair/JewelTrain-backend.git
          git push gitlab main