name: Sync to GitLab

on:
  push:
    branches:
      - main  # change if your branch is different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ⬅️ This is important!

      - name: Configure Git
        run: |
          git config --global user.email "deeprajchouhaniflair@gmail.com"
          git config --global user.name "DeepRajBytes"

      - name: Add GitLab remote and push
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/deeprajchouhaniflair/JewelTrain-backend.git || echo "Remote already exists"
          git fetch gitlab
          git push gitlab main --force

      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST \
            --form token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            --form ref=main \
            https://gitlab.com/api/v4/projects/69840445/trigger/pipeline
